apiVersion: apps/v1
kind: Deployment
metadata:
  name: mba-job-hunter-api
  namespace: staging
  labels:
    app: mba-job-hunter-api
    environment: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mba-job-hunter-api
  template:
    metadata:
      labels:
        app: mba-job-hunter-api
        environment: staging
    spec:
      containers:
      - name: api
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 8000
        env:
        - name: ENVIRONMENT
          value: "staging"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: mba-job-hunter-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: mba-job-hunter-secrets
              key: redis-url
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: mba-job-hunter-secrets
              key: secret-key
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"